### ISSUE TITLE
Question: Getting the result

### ISSUE THREAD

**Issue by sephorra** [Autodesk/theo-loader#25]
I'm just trying to work out how to use this and I was wondering if you still have to use Gulp to run the getResult plugin? I can't figure out how you get a result once you have setup the loader.

Do you have an example setup at all?

**Comment by beauroberts** [comment]
Something must be up with my Github notifications. Sorry I didn't get back to you until now!

The result is returned by the `require` statement. Here's an example from the docs:

``` js
var props = require("theo!./props.json");
// => {
//  COLOR_BACKGROUND: "rgb(244, 246, 249)",
//  COLOR_BACKGROUND_ALT: "rgb(255, 255, 255)"
// }
```

If that's not working for you, you might want to check if you have any other loaders configured to target JSON files (like json-loader). That could screw things up.

Let me know if that helps!
